#!/usr/bin/with-contenv bash

if [[ ! -f /config/feed2toot.ini ]]; then
    cp /defaults/feed2toot.ini /config/feed2toot.ini
fi

touch /config/hashtags.txt

if [[ -n ${FEED_LIMIT} ]]; then
    sed -i "s/-l [[:digit:]]\+/-l ${FEED_LIMIT}/" /etc/crontabs/abc
fi

# permissions
lsiown abc:abc \
    /config
